// Copyright 2026 Dipjyoti Metia.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//	http://www.apache.org/licenses/LICENSE-2.0

package generator

import (
	"fmt"
	"strconv"
	"strings"
	"text/template"
)

// toolLiteralSrc is the runtime.Tool registration literal, shared verbatim by
// the companion and proxy templates. Keeping it in one fragment stops the two
// emission paths from drifting — only companion output is golden-guarded, so
// a proxy-only divergence would otherwise go unnoticed.
const toolLiteralSrc = `s.AddTool(
		runtime.ApplyConfig(runtime.Tool{
			Name:           "{{.ToolName}}",
			Description:    {{quote .Description}},
			RawInputSchema: json.RawMessage({{schemaConst .ToolName}}),
			{{- if .OutputSchemaJSON}}
			RawOutputSchema: json.RawMessage({{outputSchemaConst .ToolName}}),
			{{- end}}
			{{- with annotationsLit .}}
			Annotations: {{.}},
			{{- end}}
		}, cfg),`

// schemaConstsSrc emits the input_/output_ schema string constants at the end
// of the generated file; shared by both templates for the same reason as
// toolLiteralSrc. Built with explicit \n escapes because the fragment itself
// emits Go raw-string backticks.
const schemaConstsSrc = "{{range .Ops}}\n" +
	"const {{schemaConst .ToolName}} = `{{.InputSchemaJSON}}`\n" +
	"{{if .OutputSchemaJSON}}\n" +
	"const {{outputSchemaConst .ToolName}} = `{{.OutputSchemaJSON}}`\n" +
	"{{end}}\n{{end}}\n"

// fileTemplate is the master template that emits the generated *.mcp.go file
// in companion mode. Indentation and formatting are intentionally loose; the
// output is run through gofmt before being written to disk. Companion-mode
// output is byte-for-byte stable — guarded by the golden test.
const fileTemplate = `// Code generated by openapi-go-mcp. DO NOT EDIT.
// Source: {{.SpecSource}}

package {{.PackageName}}

import (
	"context"
	"encoding/json"
	"net/http"
{{range .ExtraImports}}	{{.}}
{{end}}
	"{{.ClientImport}}"
	"github.com/dipjyotimetia/openapi-go-mcp/pkg/runtime"
)

// _ silences "imported and not used" when an operation set omits some helpers.
var _ = json.RawMessage(nil)
var _ context.Context = nil
var _ http.Header = nil

// Compile-time check: the imported package must expose the expected client
// interface. Generated code targets the typed-response variant by default.
var _ {{.ClientAlias}}.{{.ClientType}} = ({{.ClientAlias}}.{{.ClientType}})(nil)

// {{.RegisterFunc}} registers every operation in the spec as an MCP tool.
// Each tool delegates to the supplied oapi-codegen client.
func {{.RegisterFunc}}(s runtime.MCPServer, c {{.ClientAlias}}.{{.ClientType}}, opts ...runtime.Option) {
	cfg := runtime.NewConfig()
	for _, o := range opts {
		o(cfg)
	}
	{{- if .StaticPrefix}}
	if cfg.NamePrefix == "" {
		cfg.NamePrefix = "{{.StaticPrefix}}"
	}
	{{- end}}

	{{range .Ops}}
	// {{.Method}} {{.Path}}
	` + toolLiteralSrc + `
		func(ctx context.Context, req *runtime.CallToolRequest) (*runtime.CallToolResult, error) {
			ctx = runtime.ApplyExtraPropertiesToContext(ctx, req.Arguments, cfg.ExtraProperties)
			if cfg.RequestTimeout > 0 {
				var cancel context.CancelFunc
				ctx, cancel = context.WithTimeout(ctx, cfg.RequestTimeout)
				defer cancel()
			}
			{{- range .PathParams}}
			var {{.GoVar}} {{.GoType}}
			if err := runtime.DecodePathParam(req.Arguments, "{{.Name}}", &{{.GoVar}}); err != nil {
				return runtime.HandleError(err)
			}
			{{- end}}
			{{- if .HasParamsStruct}}
			var params {{$.ClientAlias}}.{{paramsTypeName .GoName}}
			if err := runtime.DecodeParamsCombined(req.Arguments, &params); err != nil {
				return runtime.HandleError(err)
			}
			{{- end}}
			{{- if .HasRequestBody}}
			{{- if isTypedBody .RequestBodyKind}}
			var body {{$.ClientAlias}}.{{bodyTypeName .GoName .RequestBodyKind}}
			if err := runtime.DecodeBody(req.Arguments, &body); err != nil {
				return runtime.HandleError(err)
			}
			{{- else if eq .RequestBodyKind "multipart"}}
			contentType, body, err := runtime.BuildMultipartBody(req.Arguments, {{fileFieldsLit .RequestFileFields}})
			if err != nil {
				return runtime.HandleError(err)
			}
			{{- else if eq .RequestBodyKind "octet"}}
			body, err := runtime.BuildBase64BytesBody(req.Arguments)
			if err != nil {
				return runtime.HandleError(err)
			}
			{{- else}}
			body, err := runtime.BuildStringBody(req.Arguments)
			if err != nil {
				return runtime.HandleError(err)
			}
			{{- end}}
			{{- end}}
			{{- if .CookieParams}}
			cookieValues := runtime.CookieValues{}
			{{- range .CookieParams}}
			{
				var v string
				if err := runtime.DecodeCookieParam(req.Arguments, "{{.Name}}", &v); err != nil {
					return runtime.HandleError(err)
				}
				cookieValues["{{.Name}}"] = v
			}
			{{- end}}
			cookieEditor := runtime.CookieRequestEditor(cookieValues)
			{{- end}}
			resp, err := c.{{.CallMethod}}(ctx{{callArgs .}})
			if err != nil {
				return runtime.HandleError(err)
			}
			if resp == nil {
				return runtime.NewToolResultError("empty response"), nil
			}
			return runtime.NewToolResultFromHTTP(
				resp.StatusCode(),
				headerOf(resp.HTTPResponse),
				resp.Body,
				{{quote .ResponseContentType}},
			), nil
		},
	)
	{{end}}
}

// headerOf returns r.Header when r is non-nil; returns nil otherwise so the
// runtime helper can use its fallback Content-Type. Generated code uses this
// instead of dereferencing resp.HTTPResponse directly because some oapi-
// codegen responses can carry a nil *http.Response (e.g. test fakes).
func headerOf(r *http.Response) http.Header {
	if r == nil {
		return nil
	}
	return r.Header
}

` + schemaConstsSrc

// fileTemplateProxy is the master template for proxy mode. It emits a
// *.mcp.go file whose handlers build *http.Request objects directly,
// dispatch through cfg.HTTPClient, and apply env-var-driven authentication
// — no oapi-codegen client needed. The companion go.mod + main.go are
// emitted separately by pkg/generator/scaffold.go.
const fileTemplateProxy = `// Code generated by openapi-go-mcp. DO NOT EDIT.
// Source: {{.SpecSource}}

package {{.PackageName}}

import (
	"context"
	"encoding/json"
	"io"
	"net/http"
	"net/url"
	"os"
	"strings"

	"github.com/dipjyotimetia/openapi-go-mcp/pkg/runtime"
)

// _ silences "imported and not used" when an operation set omits some helpers.
var _ = json.RawMessage(nil)
var _ context.Context = nil
var _ http.Header = nil
var _ io.Reader = nil
var _ = url.Values(nil)
var _ = os.Getenv
var _ = strings.ReplaceAll

// {{.RegisterFunc}} registers every operation in the spec as an MCP tool.
// Each tool proxies its arguments to the upstream HTTP service identified
// by the API_BASE_URL environment variable (default: {{.BaseURLDefault}}),
// applying authentication from environment variables derived from the
// spec's securitySchemes. See README.md for the env-var table.
func {{.RegisterFunc}}(s runtime.MCPServer, opts ...runtime.Option) {
	cfg := runtime.NewConfig()
	for _, o := range opts {
		o(cfg)
	}
	{{- if .StaticPrefix}}
	if cfg.NamePrefix == "" {
		cfg.NamePrefix = "{{.StaticPrefix}}"
	}
	{{- end}}

	baseURL := os.Getenv("API_BASE_URL")
	if baseURL == "" {
		baseURL = {{quote .BaseURLDefault}}
	}
	httpClient := cfg.HTTPClient
	if httpClient == nil {
		httpClient = http.DefaultClient
	}

	{{range .Ops}}
	// {{.Method}} {{.Path}}
	` + toolLiteralSrc + `
		func(ctx context.Context, req *runtime.CallToolRequest) (*runtime.CallToolResult, error) {
			ctx = runtime.ApplyExtraPropertiesToContext(ctx, req.Arguments, cfg.ExtraProperties)
			if cfg.RequestTimeout > 0 {
				var cancel context.CancelFunc
				ctx, cancel = context.WithTimeout(ctx, cfg.RequestTimeout)
				defer cancel()
			}
			pathStr := {{quote .Path}}
			{{- range .PathParams}}
			{
				v, _, err := runtime.DecodeProxyParam(req.Arguments, "path", "{{.Name}}", true)
				if err != nil {
					return runtime.HandleError(err)
				}
				pathStr = strings.ReplaceAll(pathStr, "{"+"{{.Name}}"+"}", runtime.PathEscape(v))
			}
			{{- end}}

			q := url.Values{}
			{{- range .QueryParams}}
			{
				v, present, err := runtime.DecodeProxyParam(req.Arguments, "query", "{{.Name}}", {{.Required}})
				if err != nil {
					return runtime.HandleError(err)
				}
				if present {
					q.Set("{{.Name}}", v)
				}
			}
			{{- end}}

			resolvedBaseURL, err := runtime.SubstituteServerVariables(baseURL, cfg.ServerVariables)
			if err != nil {
				return runtime.HandleError(err)
			}
			u, err := runtime.BuildProxyURL(resolvedBaseURL, pathStr, q)
			if err != nil {
				return runtime.HandleError(err)
			}

			var reqBody io.Reader
			var bodyCT string
			{{- if .HasRequestBody}}
			{{- if eq .RequestBodyKind "json"}}
			if raw, ok := req.Arguments["body"]; ok && raw != nil {
				reqBody, bodyCT, err = runtime.EncodeJSONBody(raw)
				if err != nil {
					return runtime.HandleError(err)
				}
			}
			{{- else if eq .RequestBodyKind "form"}}
			reqBody, bodyCT, err = runtime.EncodeFormBody(req.Arguments)
			if err != nil {
				return runtime.HandleError(err)
			}
			{{- else if eq .RequestBodyKind "multipart"}}
			mpct, mpbody, err := runtime.BuildMultipartBody(req.Arguments, {{fileFieldsLit .RequestFileFields}})
			if err != nil {
				return runtime.HandleError(err)
			}
			reqBody = mpbody
			bodyCT = mpct
			{{- else if eq .RequestBodyKind "octet"}}
			ob, err := runtime.BuildBase64BytesBody(req.Arguments)
			if err != nil {
				return runtime.HandleError(err)
			}
			reqBody = ob
			bodyCT = "application/octet-stream"
			{{- else}}
			sb, err := runtime.BuildStringBody(req.Arguments)
			if err != nil {
				return runtime.HandleError(err)
			}
			reqBody = sb
			bodyCT = {{quote .RequestContentType}}
			{{- end}}
			{{- end}}

			httpReq, err := http.NewRequestWithContext(ctx, {{quote .Method}}, u, reqBody)
			if err != nil {
				return runtime.HandleError(err)
			}
			if bodyCT != "" {
				httpReq.Header.Set("Content-Type", bodyCT)
			}

			{{- range .HeaderParams}}
			{
				v, present, err := runtime.DecodeProxyParam(req.Arguments, "header", "{{.Name}}", {{.Required}})
				if err != nil {
					return runtime.HandleError(err)
				}
				if present {
					httpReq.Header.Set("{{.Name}}", v)
				}
			}
			{{- end}}
			{{- range .CookieParams}}
			{
				v, present, err := runtime.DecodeProxyParam(req.Arguments, "cookie", "{{.Name}}", {{.Required}})
				if err != nil {
					return runtime.HandleError(err)
				}
				if present {
					httpReq.AddCookie(&http.Cookie{Name: "{{.Name}}", Value: v}) // #nosec G124
				}
			}
			{{- end}}

			{{- if .AuthRequired}}
			if err := applyAuthFor{{.GoName}}(httpReq); err != nil {
				return runtime.HandleError(err)
			}
			{{- end}}

			httpResp, err := httpClient.Do(httpReq)
			if err != nil {
				return runtime.HandleError(err)
			}
			respBody, err := runtime.ReadResponseBody(httpResp)
			if err != nil {
				return runtime.HandleError(err)
			}
			return runtime.NewToolResultFromHTTP(
				httpResp.StatusCode,
				httpResp.Header,
				respBody,
				{{quote .ResponseContentType}},
			), nil
		},
	)
	{{end}}
}

{{range .AllSchemes}}
// hasAuth{{pascalCase .Name}} reports whether the environment supplies every
// credential required for this security scheme. Policy helpers use it to
// select an OpenAPI OR alternative without sending an unauthenticated request.
func hasAuth{{pascalCase .Name}}() bool {
{{- if eq (printf "%s" .Kind) "httpBasic"}}
	return os.Getenv({{quote .UsernameEnvVar}}) != "" && os.Getenv({{quote .PasswordEnvVar}}) != ""
{{- else}}
	return os.Getenv({{quote .EnvVar}}) != ""
{{- end}}
}

// applyAuth{{pascalCase .Name}} attaches credentials for the {{quote .Name}}
// security scheme to req, reading them from the environment.
func applyAuth{{pascalCase .Name}}(req *http.Request) error {
{{- if eq (printf "%s" .Kind) "apiKey"}}
	v := os.Getenv({{quote .EnvVar}})
	if v == "" {
		return &runtime.MissingCredentialError{SchemeName: {{quote .Name}}, EnvVar: {{quote .EnvVar}}}
	}
	return runtime.ApplyAPIKey(req, runtime.AuthLocation({{quote .In}}), {{quote .ParamName}}, v)
{{- else if eq (printf "%s" .Kind) "httpBearer"}}
	v := os.Getenv({{quote .EnvVar}})
	if v == "" {
		return &runtime.MissingCredentialError{SchemeName: {{quote .Name}}, EnvVar: {{quote .EnvVar}}}
	}
	return runtime.ApplyBearer(req, v)
{{- else if eq (printf "%s" .Kind) "oauth2"}}
	v := os.Getenv({{quote .EnvVar}})
	if v == "" {
		return &runtime.MissingCredentialError{SchemeName: {{quote .Name}}, EnvVar: {{quote .EnvVar}}}
	}
	return runtime.ApplyBearer(req, v)
{{- else if eq (printf "%s" .Kind) "httpBasic"}}
	user := os.Getenv({{quote .UsernameEnvVar}})
	pass := os.Getenv({{quote .PasswordEnvVar}})
	if user == "" || pass == "" {
		return &runtime.MissingCredentialError{SchemeName: {{quote .Name}}, EnvVar: {{quote .UsernameEnvVar}} + "/" + {{quote .PasswordEnvVar}}}
	}
	return runtime.ApplyBasic(req, user, pass)
{{- end}}
}
{{end}}

{{range .Ops}}{{if .AuthRequired}}
// applyAuthFor{{.GoName}} evaluates the OpenAPI security requirement for this
// operation. Outer alternatives are OR; schemes within an alternative are AND.
// If no complete alternative has credentials, no upstream request is made.
func applyAuthFor{{.GoName}}(req *http.Request) error {
{{range .Security}}
	if {{range $index, $scheme := .}}{{if $index}} && {{end}}hasAuth{{pascalCase $scheme.Name}}(){{end}} {
		{{range .}}if err := applyAuth{{pascalCase .Name}}(req); err != nil {
			return err
		}
		{{end}}return nil
	}
{{end}}
	return &runtime.UnsatisfiedSecurityError{Operation: {{quote (printf "%s %s" .Method .Path)}}}
}
{{end}}{{end}}

` + schemaConstsSrc

// templateFuncs provides the helpers used in fileTemplate.
func templateFuncs() template.FuncMap {
	return template.FuncMap{
		"quote": goQuote,
		"schemaConst": func(toolName string) string {
			return "input_" + safeIdent(toolName)
		},
		"outputSchemaConst": func(toolName string) string {
			return "output_" + safeIdent(toolName)
		},
		"annotationsLit": annotationsLit,
		"paramsTypeName": func(goMethod string) string {
			base := strings.TrimSuffix(goMethod, "WithResponse")
			return base + "Params"
		},
		"bodyTypeName":  bodyTypeName,
		"isTypedBody":   isTypedBody,
		"fileFieldsLit": fileFieldsLit,
		"callArgs":      callArgs,
		// pascalCase renders an arbitrary identifier (currently security
		// scheme names) as a Go-safe PascalCase fragment for use inside
		// generated function names: "bearerAuth" → "BearerAuth",
		// "api-key" → "ApiKey".
		"pascalCase": PascalCase,
	}
}

// annotationsLit renders op.Annotations (computed by toolAnnotations in
// buildOperation — the policy lives there) as a *runtime.ToolAnnotations Go
// literal, or "" when the operation carries none.
func annotationsLit(op Operation) string {
	a := op.Annotations
	if a == nil {
		return ""
	}
	var fields []string
	if a.Title != "" {
		fields = append(fields, "Title: "+goQuote(a.Title))
	}
	if a.ReadOnlyHint {
		fields = append(fields, "ReadOnlyHint: true")
	}
	if a.IdempotentHint {
		fields = append(fields, "IdempotentHint: true")
	}
	if a.DestructiveHint != nil {
		fields = append(fields, fmt.Sprintf("DestructiveHint: runtime.BoolPtr(%t)", *a.DestructiveHint))
	}
	if a.OpenWorldHint != nil {
		fields = append(fields, fmt.Sprintf("OpenWorldHint: runtime.BoolPtr(%t)", *a.OpenWorldHint))
	}
	if len(fields) == 0 {
		return ""
	}
	return "&runtime.ToolAnnotations{" + strings.Join(fields, ", ") + "}"
}

// bodyTypeName returns the oapi-codegen-generated Go type name for the typed
// request body of a JSON or Form operation. Raw kinds do not use a typed body
// var and never call this helper.
func bodyTypeName(goMethod string, kind BodyKind) string {
	base := strings.TrimSuffix(goMethod, "WithResponse")
	switch kind {
	case BodyForm:
		return base + "FormdataRequestBody"
	case BodyJSON:
		fallthrough
	default:
		return base + "JSONRequestBody"
	}
}

// isTypedBody reports whether the body kind has a Go-typed body struct
// emitted by oapi-codegen (JSON or Form) versus a raw-byte / raw-string
// fallback path (multipart, octet, text, raw).
func isTypedBody(kind BodyKind) bool {
	return kind == BodyJSON || kind == BodyForm
}

// fileFieldsLit renders a []runtime.RequestFilePart Go literal describing
// each multipart binary field's JSON-pointer path, optional form field name,
// and optional per-part Content-Type. Empty input emits `nil` so a no-file
// multipart op still produces valid code. Field overrides are emitted only
// when non-empty to keep the literal compact for the common case.
func fileFieldsLit(parts []RequestFilePart) string {
	if len(parts) == 0 {
		return "nil"
	}
	var b strings.Builder
	b.WriteString("[]runtime.RequestFilePart{")
	for i, p := range parts {
		if i > 0 {
			b.WriteString(", ")
		}
		b.WriteString("{Path: ")
		b.WriteString(strconv.Quote(p.Path))
		if p.FieldName != "" {
			b.WriteString(", FieldName: ")
			b.WriteString(strconv.Quote(p.FieldName))
		}
		if p.ContentType != "" {
			b.WriteString(", ContentType: ")
			b.WriteString(strconv.Quote(p.ContentType))
		}
		b.WriteString("}")
	}
	b.WriteString("}")
	return b.String()
}

// callArgs renders the positional argument list passed to the oapi-codegen
// client method, after the leading ctx argument. Order: path params
// (positional) → params struct (pointer) if any → body args (kind-specific)
// if any.
//
// Body-arg shape by kind:
//   - JSON, Form     : "body"                   (typed value)
//   - Multipart      : "contentType, body"      (local vars from BuildMultipartBody)
//   - Octet          : `"application/octet-stream", body`
//   - Text, Raw      : `"<spec content type>", body`
//
// Returns an error rather than panicking when a BodyKind isn't handled —
// the text/template engine surfaces template-function errors through
// Execute, so a bug here fails Render() cleanly instead of producing
// broken Go that crashes downstream.
func callArgs(op Operation) (string, error) {
	var parts []string
	for _, p := range op.PathParams {
		parts = append(parts, p.GoVar)
	}
	if op.HasParamsStruct {
		parts = append(parts, "&params")
	}
	if op.HasRequestBody {
		switch op.RequestBodyKind {
		case BodyJSON, BodyForm:
			parts = append(parts, "body")
		case BodyMultipart:
			parts = append(parts, "contentType", "body")
		case BodyOctet:
			parts = append(parts, strconv.Quote("application/octet-stream"), "body")
		case BodyText, BodyRaw:
			parts = append(parts, strconv.Quote(op.RequestContentType), "body")
		default:
			return "", fmt.Errorf("callArgs: unhandled BodyKind %q on operation %s", op.RequestBodyKind, op.GoName)
		}
	}
	if len(op.CookieParams) > 0 {
		// CookieParams flow through oapi-codegen's variadic ...RequestEditorFn
		// tail. The editor closure is declared by the template alongside the
		// cookie decoding it depends on.
		parts = append(parts, "cookieEditor")
	}
	if len(parts) == 0 {
		return "", nil
	}
	return ", " + strings.Join(parts, ", "), nil
}

func goQuote(s string) string {
	var b strings.Builder
	b.WriteRune('"')
	for _, r := range s {
		switch r {
		case '\\':
			b.WriteString(`\\`)
		case '"':
			b.WriteString(`\"`)
		case '\n':
			b.WriteString(`\n`)
		case '\r':
			b.WriteString(`\r`)
		case '\t':
			b.WriteString(`\t`)
		default:
			if r < 0x20 {
				// r is guaranteed < 0x20 by the predicate above; mask to
				// satisfy gosec's rune→byte narrowing check.
				b.WriteString(`\x` + hex2(byte(r&0xff)))
			} else {
				b.WriteRune(r)
			}
		}
	}
	b.WriteRune('"')
	return b.String()
}

func hex2(b byte) string {
	const hex = "0123456789abcdef"
	return string([]byte{hex[b>>4], hex[b&0xf]})
}

func safeIdent(s string) string {
	var b strings.Builder
	for _, r := range s {
		switch {
		case r >= 'a' && r <= 'z', r >= 'A' && r <= 'Z', r >= '0' && r <= '9':
			b.WriteRune(r)
		default:
			b.WriteRune('_')
		}
	}
	return b.String()
}
