// Copyright 2026 Dipjyoti Metia.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//	http://www.apache.org/licenses/LICENSE-2.0

package generator

import (
	"fmt"
	"sort"
	"strconv"
	"strings"
	"text/template"
)

// toolLiteralSrc is the runtime.Tool registration literal, shared verbatim by
// the companion and proxy templates. Keeping it in one fragment stops the two
// emission paths from drifting — only companion output is golden-guarded, so
// a proxy-only divergence would otherwise go unnoticed.
const toolLiteralSrc = `s.AddTool(
		runtime.ApplyConfig(runtime.Tool{
			Name:           "{{.ToolName}}",
			Description:    {{quote .Description}},
			RawInputSchema: {{if $.ProviderAware}}inputSchemaForProvider(provider, {{schemaConst .ToolName}}, {{openAISchemaConst .ToolName}}){{else}}json.RawMessage({{schemaConst .ToolName}}){{end}},
			{{- if .OutputSchemaJSON}}
			RawOutputSchema: json.RawMessage({{outputSchemaConst .ToolName}}),
			{{- end}}
			{{- with annotationsLit .}}
			Annotations: {{.}},
			{{- end}}
		}, cfg),`

// schemaConstsSrc emits the input_/output_ schema string constants at the end
// of the generated file; shared by both templates for the same reason as
// toolLiteralSrc. Built with explicit \n escapes because the fragment itself
// emits Go raw-string backticks.
const schemaConstsSrc = "{{range .Ops}}\n" +
	"const {{schemaConst .ToolName}} = `{{.InputSchemaJSON}}`\n" +
	"{{if $.ProviderAware}}\nconst {{openAISchemaConst .ToolName}} = `{{.InputSchemaOpenAIJSON}}`\n{{end}}" +
	"{{if .OutputSchemaJSON}}\n" +
	"const {{outputSchemaConst .ToolName}} = `{{.OutputSchemaJSON}}`\n" +
	"{{end}}\n{{end}}\n"

// fileTemplate is the master template that emits the generated *.mcp.go file
// in companion mode. Indentation and formatting are intentionally loose; the
// output is run through gofmt before being written to disk. Companion-mode
// output is byte-for-byte stable — guarded by the golden test.
const fileTemplate = `// Code generated by openapi-go-mcp. DO NOT EDIT.
// Source: {{.SpecSource}}

package {{.PackageName}}

import (
	"context"
	"encoding/json"
	"net/http"
{{range .ExtraImports}}	{{.}}
{{end}}
	"{{.ClientImport}}"
	"github.com/dipjyotimetia/openapi-go-mcp/pkg/runtime"
)

// _ silences "imported and not used" when an operation set omits some helpers.
var _ = json.RawMessage(nil)
var _ context.Context = nil
var _ http.Header = nil

// Compile-time check: the imported package must expose the expected client
// interface. Generated code targets the typed-response variant by default.
var _ {{.ClientAlias}}.{{.ClientType}} = ({{.ClientAlias}}.{{.ClientType}})(nil)

{{if .ProviderAware}}// {{.RegisterFunc}} registers every operation in the spec with the standard
// MCP-compatible input schema. Each tool delegates to the supplied oapi-codegen client.
{{else}}// {{.RegisterFunc}} registers every operation in the spec as an MCP tool.
// Each tool delegates to the supplied oapi-codegen client.
{{end -}}
func {{.RegisterFunc}}(s runtime.MCPServer, c {{.ClientAlias}}.{{.ClientType}}, opts ...runtime.Option) {
	{{if .ProviderAware}}{{.RegisterFunc}}WithProvider(s, c, runtime.LLMProviderStandard, opts...)
}

// {{.RegisterFunc}}OpenAI registers every operation with OpenAI-compatible
// input schemas.
func {{.RegisterFunc}}OpenAI(s runtime.MCPServer, c {{.ClientAlias}}.{{.ClientType}}, opts ...runtime.Option) {
	{{.RegisterFunc}}WithProvider(s, c, runtime.LLMProviderOpenAI, opts...)
}

// {{.RegisterFunc}}WithProvider registers every operation using the schema
// dialect selected by provider. Unknown providers use the standard schema.
func {{.RegisterFunc}}WithProvider(s runtime.MCPServer, c {{.ClientAlias}}.{{.ClientType}}, provider runtime.LLMProvider, opts ...runtime.Option) {
	{{end}}
	cfg := runtime.NewConfig()
	for _, o := range opts {
		o(cfg)
	}
	{{- if .StaticPrefix}}
	if cfg.NamePrefix == "" {
		cfg.NamePrefix = "{{.StaticPrefix}}"
	}
	{{- end}}

	{{range .Ops}}
	// {{.Method}} {{.Path}}
	` + toolLiteralSrc + `
		func(ctx context.Context, req *runtime.CallToolRequest) (*runtime.CallToolResult, error) {
			ctx = runtime.ApplyExtraPropertiesToContext(ctx, req.Arguments, cfg.ExtraProperties)
			if cfg.RequestTimeout > 0 {
				var cancel context.CancelFunc
				ctx, cancel = context.WithTimeout(ctx, cfg.RequestTimeout)
				defer cancel()
			}
			{{- range .PathParams}}
			var {{.GoVar}} {{.GoType}}
			if err := runtime.DecodePathParam(req.Arguments, "{{.Name}}", &{{.GoVar}}); err != nil {
				return runtime.HandleError(err)
			}
			{{- end}}
			{{- if .HasParamsStruct}}
			var params {{$.ClientAlias}}.{{paramsTypeName .GoName}}
			if err := runtime.DecodeParamsCombined(req.Arguments, &params); err != nil {
				return runtime.HandleError(err)
			}
			{{- end}}
			{{- if .HasRequestBody}}
			{{- if isTypedBody .RequestBodyKind}}
			var body {{$.ClientAlias}}.{{bodyTypeName .GoName .RequestBodyKind}}
			if err := runtime.DecodeBody(req.Arguments, &body); err != nil {
				return runtime.HandleError(err)
			}
			{{- else if eq .RequestBodyKind "multipart"}}
			contentType, body, err := runtime.BuildMultipartBody(req.Arguments, {{fileFieldsLit .RequestFileFields}})
			if err != nil {
				return runtime.HandleError(err)
			}
			{{- else if eq .RequestBodyKind "octet"}}
			body, err := runtime.BuildBase64BytesBody(req.Arguments)
			if err != nil {
				return runtime.HandleError(err)
			}
			{{- else}}
			body, err := runtime.BuildStringBody(req.Arguments)
			if err != nil {
				return runtime.HandleError(err)
			}
			{{- end}}
			{{- end}}
			{{- if .CookieParams}}
			cookieValues := runtime.CookieValues{}
			{{- range .CookieParams}}
			{
				var v string
				if err := runtime.DecodeCookieParam(req.Arguments, "{{.Name}}", &v); err != nil {
					return runtime.HandleError(err)
				}
				cookieValues["{{.Name}}"] = v
			}
			{{- end}}
			cookieEditor := runtime.CookieRequestEditor(cookieValues)
			{{- end}}
			resp, err := c.{{.CallMethod}}(ctx{{callArgs .}})
			if err != nil {
				return runtime.HandleError(err)
			}
			if resp == nil {
				return runtime.NewToolResultError("empty response"), nil
			}
			return runtime.NewToolResultFromHTTP(
				resp.StatusCode(),
				headerOf(resp.HTTPResponse),
				resp.Body,
				{{quote .ResponseContentType}},
			), nil
		},
	)
	{{end}}
}

// headerOf returns r.Header when r is non-nil; returns nil otherwise so the
// runtime helper can use its fallback Content-Type. Generated code uses this
// instead of dereferencing resp.HTTPResponse directly because some oapi-
// codegen responses can carry a nil *http.Response (e.g. test fakes).
func headerOf(r *http.Response) http.Header {
	if r == nil {
		return nil
	}
	return r.Header
}

{{if .ProviderAware}}
// inputSchemaForProvider returns OpenAI's strict schema only for the OpenAI
// provider; all other values deliberately retain the standard MCP schema.
func inputSchemaForProvider(provider runtime.LLMProvider, standard, openAI string) json.RawMessage {
	if provider == runtime.LLMProviderOpenAI {
		return json.RawMessage(openAI)
	}
	return json.RawMessage(standard)
}
{{end}}

` + schemaConstsSrc

// fileTemplateProxy is the master template for proxy mode. It emits a
// *.mcp.go file whose handlers build *http.Request objects directly,
// dispatch through cfg.HTTPClient, and apply env-var-driven authentication
// — no oapi-codegen client needed. The companion go.mod + main.go are
// emitted separately by pkg/generator/scaffold.go.
const fileTemplateProxy = `// Code generated by openapi-go-mcp. DO NOT EDIT.
// Source: {{.SpecSource}}

package {{.PackageName}}

import (
	"context"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"os"
	"strings"
	"sync"

	"github.com/dipjyotimetia/openapi-go-mcp/pkg/runtime"
)

// _ silences "imported and not used" when an operation set omits some helpers.
var _ = json.RawMessage(nil)
var _ = fmt.Errorf
var _ context.Context = nil
var _ http.Header = nil
var _ io.Reader = nil
var _ = os.Getenv
var _ = strings.ReplaceAll
var _ sync.Mutex

{{if .ProviderAware}}// {{.RegisterFunc}} registers every operation in the spec with the standard
// MCP-compatible input schema.
{{else}}// {{.RegisterFunc}} registers every operation in the spec as an MCP tool.
{{end -}}
// Each tool proxies its arguments to the upstream HTTP service identified
// by the API_BASE_URL environment variable (default: {{.BaseURLDefault}}),
// applying authentication from environment variables derived from the
// spec's securitySchemes. See README.md for the env-var table.
func {{.RegisterFunc}}(s runtime.MCPServer, opts ...runtime.Option) {
	{{if .ProviderAware}}{{.RegisterFunc}}WithProvider(s, runtime.LLMProviderStandard, opts...)
}

// {{.RegisterFunc}}OpenAI registers every operation with OpenAI-compatible
// input schemas.
func {{.RegisterFunc}}OpenAI(s runtime.MCPServer, opts ...runtime.Option) {
	{{.RegisterFunc}}WithProvider(s, runtime.LLMProviderOpenAI, opts...)
}

// {{.RegisterFunc}}WithProvider registers every operation using the schema
// dialect selected by provider. Unknown providers use the standard schema.
func {{.RegisterFunc}}WithProvider(s runtime.MCPServer, provider runtime.LLMProvider, opts ...runtime.Option) {
	{{end}}
	cfg := runtime.NewConfig()
	for _, o := range opts {
		o(cfg)
	}
	{{- if .StaticPrefix}}
	if cfg.NamePrefix == "" {
		cfg.NamePrefix = "{{.StaticPrefix}}"
	}
	{{- end}}

	baseURL := os.Getenv("API_BASE_URL")
	if baseURL == "" {
		baseURL = {{quote .BaseURLDefault}}
	}
	httpClient := cfg.HTTPClient
	if httpClient == nil {
		httpClient = http.DefaultClient
	}

	{{range .Ops}}
	// {{.Method}} {{.Path}}
	` + toolLiteralSrc + `
		func(ctx context.Context, req *runtime.CallToolRequest) (*runtime.CallToolResult, error) {
			ctx = runtime.ApplyExtraPropertiesToContext(ctx, req.Arguments, cfg.ExtraProperties)
			if cfg.RequestTimeout > 0 {
				var cancel context.CancelFunc
				ctx, cancel = context.WithTimeout(ctx, cfg.RequestTimeout)
				defer cancel()
			}
			pathStr := {{quote .Path}}
			{{- range .PathParams}}
			{
				param, _, err := runtime.SerializeProxyParam(req.Arguments, runtime.ProxyParamSpec{Name: "{{.Name}}", In: "path", Style: {{quote .Style}}, Explode: {{.Explode}}, AllowReserved: {{.AllowReserved}}}, true)
				if err != nil {
					return runtime.HandleError(err)
				}
				pathStr = strings.ReplaceAll(pathStr, "{"+"{{.Name}}"+"}", param.Value)
			}
			{{- end}}

			q := runtime.ProxyQuery{}
			{{- range .QueryParams}}
			{
				param, present, err := runtime.SerializeProxyParam(req.Arguments, runtime.ProxyParamSpec{Name: "{{.Name}}", In: "query", Style: {{quote .Style}}, Explode: {{.Explode}}, AllowReserved: {{.AllowReserved}}}, {{.Required}})
				if err != nil {
					return runtime.HandleError(err)
				}
				if present {
					q = append(q, param.Query...)
				}
			}
			{{- end}}

			resolvedBaseURL, err := runtime.SubstituteServerVariables(baseURL, cfg.ServerVariables)
			if err != nil {
				return runtime.HandleError(err)
			}
			u, err := runtime.BuildProxyURL(resolvedBaseURL, pathStr, q)
			if err != nil {
				return runtime.HandleError(err)
			}

			var reqBody io.Reader
			var bodyCT string
			{{- if .HasRequestBody}}
			{{- if eq .RequestBodyKind "json"}}
			if raw, ok := req.Arguments["body"]; ok && raw != nil {
				reqBody, bodyCT, err = runtime.EncodeJSONBody(raw)
				if err != nil {
					return runtime.HandleError(err)
				}
			}
			{{- else if eq .RequestBodyKind "form"}}
			reqBody, bodyCT, err = runtime.EncodeFormBody(req.Arguments)
			if err != nil {
				return runtime.HandleError(err)
			}
			{{- else if eq .RequestBodyKind "multipart"}}
			mpct, mpbody, err := runtime.BuildMultipartBody(req.Arguments, {{fileFieldsLit .RequestFileFields}})
			if err != nil {
				return runtime.HandleError(err)
			}
			reqBody = mpbody
			bodyCT = mpct
			{{- else if eq .RequestBodyKind "octet"}}
			ob, err := runtime.BuildBase64BytesBody(req.Arguments)
			if err != nil {
				return runtime.HandleError(err)
			}
			reqBody = ob
			bodyCT = "application/octet-stream"
			{{- else}}
			sb, err := runtime.BuildStringBody(req.Arguments)
			if err != nil {
				return runtime.HandleError(err)
			}
			reqBody = sb
			bodyCT = {{quote .RequestContentType}}
			{{- end}}
			{{- end}}

			httpReq, err := http.NewRequestWithContext(ctx, {{quote .Method}}, u, reqBody)
			if err != nil {
				return runtime.HandleError(err)
			}
			if bodyCT != "" {
				httpReq.Header.Set("Content-Type", bodyCT)
			}

			{{- range .HeaderParams}}
			{
				param, present, err := runtime.SerializeProxyParam(req.Arguments, runtime.ProxyParamSpec{Name: "{{.Name}}", In: "header", Style: {{quote .Style}}, Explode: {{.Explode}}, AllowReserved: {{.AllowReserved}}}, {{.Required}})
				if err != nil {
					return runtime.HandleError(err)
				}
				if present {
					httpReq.Header.Set("{{.Name}}", param.Value)
				}
			}
			{{- end}}
			{{- range .CookieParams}}
			{
				param, present, err := runtime.SerializeProxyParam(req.Arguments, runtime.ProxyParamSpec{Name: "{{.Name}}", In: "cookie", Style: {{quote .Style}}, Explode: {{.Explode}}, AllowReserved: {{.AllowReserved}}}, {{.Required}})
				if err != nil {
					return runtime.HandleError(err)
				}
				if present {
					for _, cookie := range param.Cookies {
						httpReq.AddCookie(&http.Cookie{Name: cookie.Name, Value: cookie.Value}) // #nosec G124
					}
				}
			}
			{{- end}}

			{{- if .AuthRequired}}
			if err := applyAuthFor{{.GoName}}(ctx, httpReq, cfg); err != nil {
				return runtime.HandleError(err)
			}
			{{- end}}

			httpResp, err := httpClient.Do(httpReq)
			if err != nil {
				return runtime.HandleError(err)
			}
			respBody, err := runtime.ReadResponseBodyLimit(httpResp, cfg.MaxResponseBytes)
			if err != nil {
				return runtime.HandleError(err)
			}
			return runtime.NewToolResultFromHTTP(
				httpResp.StatusCode,
				httpResp.Header,
				respBody,
				{{quote .ResponseContentType}},
			), nil
		},
	)
	{{end}}
}

{{range .AllSchemes}}
// hasAuth{{pascalCase .Name}} reports whether the environment supplies every
// credential required for this security scheme. Policy helpers use it to
// select an OpenAPI OR alternative without sending an unauthenticated request.
func hasAuth{{pascalCase .Name}}(cfg *runtime.Config) bool {
{{- if eq (printf "%s" .Kind) "httpBasic"}}
	return os.Getenv({{quote .UsernameEnvVar}}) != "" && os.Getenv({{quote .PasswordEnvVar}}) != ""
{{- else if eq (printf "%s" .Kind) "custom"}}
	return cfg.RequestAuthProvider != nil
{{- else if eq (printf "%s" .Kind) "mtls"}}
	return cfg.MTLSConfigured
{{- else if and (eq (printf "%s" .Kind) "oauth2") .OAuthTokenURL}}
	return os.Getenv({{quote .EnvVar}}) != "" || (os.Getenv({{quote .ClientIDEnvVar}}) != "" && os.Getenv({{quote .ClientSecretEnvVar}}) != "")
{{- else}}
	return os.Getenv({{quote .EnvVar}}) != ""
{{- end}}
}

// applyAuth{{pascalCase .Name}} attaches credentials for the {{quote .Name}}
// security scheme to req, reading them from the environment.
func applyAuth{{pascalCase .Name}}(ctx context.Context, req *http.Request, cfg *runtime.Config) error {
{{- if eq (printf "%s" .Kind) "apiKey"}}
	v := os.Getenv({{quote .EnvVar}})
	if v == "" {
		return &runtime.MissingCredentialError{SchemeName: {{quote .Name}}, EnvVar: {{quote .EnvVar}}}
	}
	return runtime.ApplyAPIKey(req, runtime.AuthLocation({{quote .In}}), {{quote .ParamName}}, v)
{{- else if eq (printf "%s" .Kind) "httpBearer"}}
	v := os.Getenv({{quote .EnvVar}})
	if v == "" {
		return &runtime.MissingCredentialError{SchemeName: {{quote .Name}}, EnvVar: {{quote .EnvVar}}}
	}
	return runtime.ApplyBearer(req, v)
{{- else if eq (printf "%s" .Kind) "oauth2"}}
	v := os.Getenv({{quote .EnvVar}})
	if v != "" {
		return runtime.ApplyBearer(req, v)
	}
{{- if .OAuthTokenURL}}
	return applyOAuthClientCredentials{{pascalCase .Name}}(ctx, req)
{{- else}}
	return &runtime.MissingCredentialError{SchemeName: {{quote .Name}}, EnvVar: {{quote .EnvVar}}}
{{- end}}
{{- else if eq (printf "%s" .Kind) "httpBasic"}}
	user := os.Getenv({{quote .UsernameEnvVar}})
	pass := os.Getenv({{quote .PasswordEnvVar}})
	if user == "" || pass == "" {
		return &runtime.MissingCredentialError{SchemeName: {{quote .Name}}, EnvVar: {{quote .UsernameEnvVar}} + "/" + {{quote .PasswordEnvVar}}}
	}
	return runtime.ApplyBasic(req, user, pass)
{{- else if eq (printf "%s" .Kind) "custom"}}
	return runtime.ApplyRequestAuth(ctx, req, cfg.RequestAuthProvider)
{{- else if eq (printf "%s" .Kind) "mtls"}}
	if !cfg.MTLSConfigured {
		return fmt.Errorf("mTLS client is not configured for security scheme %s", {{quote .Name}})
	}
	return nil
{{- end}}
}
{{if and (eq (printf "%s" .Kind) "oauth2") .OAuthTokenURL}}

var oauthClientCredentials{{pascalCase .Name}} struct {
	sync.Mutex
	provider *runtime.ClientCredentialsProvider
	clientID string
	clientSecret string
}

func applyOAuthClientCredentials{{pascalCase .Name}}(ctx context.Context, req *http.Request) error {
	clientID := os.Getenv({{quote .ClientIDEnvVar}})
	clientSecret := os.Getenv({{quote .ClientSecretEnvVar}})
	if clientID == "" || clientSecret == "" {
		return &runtime.MissingCredentialError{SchemeName: {{quote .Name}}, EnvVar: {{quote .ClientIDEnvVar}} + "/" + {{quote .ClientSecretEnvVar}}}
	}
	oauthClientCredentials{{pascalCase .Name}}.Lock()
	if oauthClientCredentials{{pascalCase .Name}}.provider == nil || oauthClientCredentials{{pascalCase .Name}}.clientID != clientID || oauthClientCredentials{{pascalCase .Name}}.clientSecret != clientSecret {
		provider, err := runtime.NewClientCredentialsProvider(runtime.ClientCredentialsConfig{TokenURL: {{quote .OAuthTokenURL}}, ClientID: clientID, ClientSecret: clientSecret, Scopes: []string{ {{range $index, $scope := .OAuthScopes}}{{if $index}}, {{end}}{{quote $scope}}{{end}} }})
		if err != nil {
			oauthClientCredentials{{pascalCase .Name}}.Unlock()
			return err
		}
		oauthClientCredentials{{pascalCase .Name}}.provider = provider
		oauthClientCredentials{{pascalCase .Name}}.clientID = clientID
		oauthClientCredentials{{pascalCase .Name}}.clientSecret = clientSecret
	}
	provider := oauthClientCredentials{{pascalCase .Name}}.provider
	oauthClientCredentials{{pascalCase .Name}}.Unlock()
	return provider.Apply(ctx, req)
}
{{end}}
{{end}}

{{range .Ops}}{{if .AuthRequired}}
// applyAuthFor{{.GoName}} evaluates the OpenAPI security requirement for this
// operation. Outer alternatives are OR; schemes within an alternative are AND.
// If no complete alternative has credentials, no upstream request is made.
func applyAuthFor{{.GoName}}(ctx context.Context, req *http.Request, cfg *runtime.Config) error {
{{range .Security}}
	if {{range $index, $scheme := .}}{{if $index}} && {{end}}hasAuth{{pascalCase $scheme.Name}}(cfg){{end}} {
		{{range .}}if err := applyAuth{{pascalCase .Name}}(ctx, req, cfg); err != nil {
			return err
		}
		{{end}}return nil
	}
{{end}}
	return &runtime.UnsatisfiedSecurityError{Operation: {{quote (printf "%s %s" .Method .Path)}}, MissingEnvVars: {{securityEnvVarsLit .Security}}}
}
{{end}}{{end}}

{{if .ProviderAware}}
// inputSchemaForProvider returns OpenAI's strict schema only for the OpenAI
// provider; all other values deliberately retain the standard MCP schema.
func inputSchemaForProvider(provider runtime.LLMProvider, standard, openAI string) json.RawMessage {
	if provider == runtime.LLMProviderOpenAI {
		return json.RawMessage(openAI)
	}
	return json.RawMessage(standard)
}
{{end}}

` + schemaConstsSrc

// templateFuncs provides the helpers used in fileTemplate.
func templateFuncs() template.FuncMap {
	return template.FuncMap{
		"quote": goQuote,
		"schemaConst": func(toolName string) string {
			return "input_" + safeIdent(toolName)
		},
		"openAISchemaConst": func(toolName string) string {
			return "input_openai_" + safeIdent(toolName)
		},
		"outputSchemaConst": func(toolName string) string {
			return "output_" + safeIdent(toolName)
		},
		"annotationsLit": annotationsLit,
		"paramsTypeName": func(goMethod string) string {
			base := strings.TrimSuffix(goMethod, "WithResponse")
			return base + "Params"
		},
		"bodyTypeName":  bodyTypeName,
		"isTypedBody":   isTypedBody,
		"fileFieldsLit": fileFieldsLit,
		"callArgs":      callArgs,
		// pascalCase renders an arbitrary identifier (currently security
		// scheme names) as a Go-safe PascalCase fragment for use inside
		// generated function names: "bearerAuth" → "BearerAuth",
		// "api-key" → "ApiKey".
		"pascalCase":         PascalCase,
		"securityEnvVarsLit": securityEnvVarsLit,
	}
}

// securityEnvVarsLit renders the stable, deduplicated environment-variable
// names that could satisfy any security alternative. It makes a fail-closed
// generated error actionable without exposing credential values.
func securityEnvVarsLit(alternatives [][]SecurityScheme) string {
	seen := map[string]struct{}{}
	var vars []string
	for _, alternative := range alternatives {
		for _, scheme := range alternative {
			if scheme.Kind == SecurityHTTPBasic {
				seen[scheme.UsernameEnvVar] = struct{}{}
				seen[scheme.PasswordEnvVar] = struct{}{}
				continue
			}
			if scheme.Kind == SecurityOAuth2 && scheme.OAuthTokenURL != "" {
				seen[scheme.ClientIDEnvVar] = struct{}{}
				seen[scheme.ClientSecretEnvVar] = struct{}{}
			}
			seen[scheme.EnvVar] = struct{}{}
		}
	}
	for envVar := range seen {
		if envVar != "" {
			vars = append(vars, envVar)
		}
	}
	sort.Strings(vars)
	if len(vars) == 0 {
		return "nil"
	}
	parts := make([]string, 0, len(vars))
	for _, envVar := range vars {
		parts = append(parts, strconv.Quote(envVar))
	}
	return "[]string{" + strings.Join(parts, ", ") + "}"
}

// annotationsLit renders op.Annotations (computed by toolAnnotations in
// buildOperation — the policy lives there) as a *runtime.ToolAnnotations Go
// literal, or "" when the operation carries none.
func annotationsLit(op Operation) string {
	a := op.Annotations
	if a == nil {
		return ""
	}
	var fields []string
	if a.Title != "" {
		fields = append(fields, "Title: "+goQuote(a.Title))
	}
	if a.ReadOnlyHint {
		fields = append(fields, "ReadOnlyHint: true")
	}
	if a.IdempotentHint {
		fields = append(fields, "IdempotentHint: true")
	}
	if a.DestructiveHint != nil {
		fields = append(fields, fmt.Sprintf("DestructiveHint: runtime.BoolPtr(%t)", *a.DestructiveHint))
	}
	if a.OpenWorldHint != nil {
		fields = append(fields, fmt.Sprintf("OpenWorldHint: runtime.BoolPtr(%t)", *a.OpenWorldHint))
	}
	if len(fields) == 0 {
		return ""
	}
	return "&runtime.ToolAnnotations{" + strings.Join(fields, ", ") + "}"
}

// bodyTypeName returns the oapi-codegen-generated Go type name for the typed
// request body of a JSON or Form operation. Raw kinds do not use a typed body
// var and never call this helper.
func bodyTypeName(goMethod string, kind BodyKind) string {
	base := strings.TrimSuffix(goMethod, "WithResponse")
	switch kind {
	case BodyForm:
		return base + "FormdataRequestBody"
	case BodyJSON:
		fallthrough
	default:
		return base + "JSONRequestBody"
	}
}

// isTypedBody reports whether the body kind has a Go-typed body struct
// emitted by oapi-codegen (JSON or Form) versus a raw-byte / raw-string
// fallback path (multipart, octet, text, raw).
func isTypedBody(kind BodyKind) bool {
	return kind == BodyJSON || kind == BodyForm
}

// fileFieldsLit renders a []runtime.RequestFilePart Go literal describing
// each multipart binary field's JSON-pointer path, optional form field name,
// and optional per-part Content-Type. Empty input emits `nil` so a no-file
// multipart op still produces valid code. Field overrides are emitted only
// when non-empty to keep the literal compact for the common case.
func fileFieldsLit(parts []RequestFilePart) string {
	if len(parts) == 0 {
		return "nil"
	}
	var b strings.Builder
	b.WriteString("[]runtime.RequestFilePart{")
	for i, p := range parts {
		if i > 0 {
			b.WriteString(", ")
		}
		b.WriteString("{Path: ")
		b.WriteString(strconv.Quote(p.Path))
		if p.FieldName != "" {
			b.WriteString(", FieldName: ")
			b.WriteString(strconv.Quote(p.FieldName))
		}
		if p.ContentType != "" {
			b.WriteString(", ContentType: ")
			b.WriteString(strconv.Quote(p.ContentType))
		}
		b.WriteString("}")
	}
	b.WriteString("}")
	return b.String()
}

// callArgs renders the positional argument list passed to the oapi-codegen
// client method, after the leading ctx argument. Order: path params
// (positional) → params struct (pointer) if any → body args (kind-specific)
// if any.
//
// Body-arg shape by kind:
//   - JSON, Form     : "body"                   (typed value)
//   - Multipart      : "contentType, body"      (local vars from BuildMultipartBody)
//   - Octet          : `"application/octet-stream", body`
//   - Text, Raw      : `"<spec content type>", body`
//
// Returns an error rather than panicking when a BodyKind isn't handled —
// the text/template engine surfaces template-function errors through
// Execute, so a bug here fails Render() cleanly instead of producing
// broken Go that crashes downstream.
func callArgs(op Operation) (string, error) {
	var parts []string
	for _, p := range op.PathParams {
		parts = append(parts, p.GoVar)
	}
	if op.HasParamsStruct {
		parts = append(parts, "&params")
	}
	if op.HasRequestBody {
		switch op.RequestBodyKind {
		case BodyJSON, BodyForm:
			parts = append(parts, "body")
		case BodyMultipart:
			parts = append(parts, "contentType", "body")
		case BodyOctet:
			parts = append(parts, strconv.Quote("application/octet-stream"), "body")
		case BodyText, BodyRaw:
			parts = append(parts, strconv.Quote(op.RequestContentType), "body")
		default:
			return "", fmt.Errorf("callArgs: unhandled BodyKind %q on operation %s", op.RequestBodyKind, op.GoName)
		}
	}
	if len(op.CookieParams) > 0 {
		// CookieParams flow through oapi-codegen's variadic ...RequestEditorFn
		// tail. The editor closure is declared by the template alongside the
		// cookie decoding it depends on.
		parts = append(parts, "cookieEditor")
	}
	if len(parts) == 0 {
		return "", nil
	}
	return ", " + strings.Join(parts, ", "), nil
}

func goQuote(s string) string {
	var b strings.Builder
	b.WriteRune('"')
	for _, r := range s {
		switch r {
		case '\\':
			b.WriteString(`\\`)
		case '"':
			b.WriteString(`\"`)
		case '\n':
			b.WriteString(`\n`)
		case '\r':
			b.WriteString(`\r`)
		case '\t':
			b.WriteString(`\t`)
		default:
			if r < 0x20 {
				// r is guaranteed < 0x20 by the predicate above; mask to
				// satisfy gosec's rune→byte narrowing check.
				b.WriteString(`\x` + hex2(byte(r&0xff)))
			} else {
				b.WriteRune(r)
			}
		}
	}
	b.WriteRune('"')
	return b.String()
}

func hex2(b byte) string {
	const hex = "0123456789abcdef"
	return string([]byte{hex[b>>4], hex[b&0xf]})
}

func safeIdent(s string) string {
	var b strings.Builder
	for _, r := range s {
		switch {
		case r >= 'a' && r <= 'z', r >= 'A' && r <= 'Z', r >= '0' && r <= '9':
			b.WriteRune(r)
		default:
			b.WriteRune('_')
		}
	}
	return b.String()
}
